# Generated by Django 5.1.1 on 2024-09-10 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('your_name', models.CharField(max_length=100)),
                ('company_gstin', models.CharField(max_length=50)),
                ('company_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('client_company', models.CharField(max_length=100)),
                ('client_gstin', models.CharField(max_length=50)),
                ('client_address', models.TextField()),
                ('client_city', models.CharField(max_length=100)),
                ('client_state', models.CharField(max_length=100)),
                ('client_country', models.CharField(max_length=100)),
                ('invoice', models.CharField(max_length=50)),
                ('datetime_field1', models.DateTimeField()),
                ('datetime_field2', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_desc', models.CharField(max_length=255)),
                ('qty', models.FloatField()),
                ('rate', models.FloatField()),
                ('sgst', models.FloatField()),
                ('cgst', models.FloatField()),
                ('cess', models.FloatField()),
                ('myformdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.myformdata')),
            ],
        ),
    ]
