# Generated by Django 5.0.7 on 2024-09-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_myformdata_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gst_rate',
            field=models.PositiveIntegerField(choices=[(0, '0%'), (5, '5%'), (12, '12%'), (18, '18%'), (28, '28%')], default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='cess',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='item',
            name='cgst',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='item',
            name='sgst',
            field=models.FloatField(default=0.0),
        ),
    ]
