# Generated by Django 5.1 on 2024-09-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_item_gst_rate_alter_item_cess_alter_item_cgst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myformdata',
            name='city',
            field=models.CharField(choices=[('New York', 'New York'), ('Los Angeles', 'Los Angeles'), ('Chicago', 'Chicago')], max_length=100),
        ),
    ]
