# Generated by Django 5.1 on 2024-09-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_myformdata_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myformdata',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
