# Generated by Django 5.1 on 2024-09-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_myformdata_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='myformdata',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myformdata',
            name='terms_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
