# Generated by Django 5.0.7 on 2024-09-20 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_myformdata_notes_myformdata_terms_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('your_name', models.CharField(max_length=100)),
                ('company_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('report_from', models.TextField()),
                ('report_to', models.TextField()),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('invoice_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('expense_description', models.CharField(max_length=255)),
                ('merchant', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('expense_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='myapp.expensereport')),
            ],
        ),
    ]
